# Generated by Django 4.1.1 on 2022-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='weather_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
