# Generated by Django 4.1.1 on 2022-12-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_search', '0002_searchhistory_weather_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='city_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
